---
title: 'Übung 02: Verfahrens- und Maschinenfehler'
author: "Tobias Blesgen und Leonardo Thome"
date: "19.05.2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes: 
 - \usepackage{amssymb}
 - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Stuff to do:
- Einleitungstexte schreiben
- 2-Punktformel, Variation von Schrittweite k -> Fehler aufzeichnen
- 


# Verfahrens- und Maschinenfehler

## Maschinenfehler

## Verfahrensfehler

## Beispiel Anhand der Differentation

Am Beispiel der Differentation der Funktion $f(x) = e^x$ an der Stelle x = 2 sollen die Fehlertypen aufgezeigt werden.

```{Rcpp}
#include <Rcpp.h>
#include <math.h>

using namespace Rcpp;

//[[Rcpp::export]]
Rcpp::List diff2PunktDouble(const double x, const int r){
  // Array der ersten 100 Werte:
    Rcpp::NumericVector xValue(100);
    Rcpp::NumericVector yValue(100);
  // Quelltext
    for (int i = r; i<=99+r; i++){
      xValue[i-r] = 1./i;
      yValue[i-r] = (exp(x+1./i) - exp(x))/(1./i);
    }
  // Rückgabe für eine grafische Wiedergabe
    return List::create(Named("x") = xValue, Named("y") = yValue);
}
```

```{Rcpp,echo=FALSE}
#include <Rcpp.h>
#include <math.h>

using namespace Rcpp;

//[[Rcpp::export]]
Rcpp::List diff2PunktFloat(const float x, const int r){
  // Array der ersten 100 Werte:
    Rcpp::NumericVector xValue(100);
    Rcpp::NumericVector yValue(100);
  // Quelltext
    for (int i = r; i<=99+r; i++){
      xValue[i-r] = (float)1./i;
      yValue[i-r] = (float)(exp(x+1./i) - exp(x))/(1./i);
    }
  // Rückgabe für eine grafische Wiedergabe
    return List::create(Named("x") = xValue, Named("y") = yValue);
}
```

```{Rcpp}
#include <Rcpp.h>
#include <math.h>

using namespace Rcpp;

//[[Rcpp::export]]
Rcpp::List diff3PunktDouble(const double x, const int r){
  // Array der ersten 100 Werte:
    Rcpp::NumericVector xValue(100);
    Rcpp::NumericVector yValue(100);
  // Quelltext
    for (int i = r; i<=99+r; i++){
      xValue[i-r] = 1./i;
      yValue[i-r] = (exp(x+1./i) - exp(x-1./i))/(2./i);
    }
  // Rückgabe für eine grafische Wiedergabe
    return List::create(Named("x") = xValue, Named("y") = yValue);
}
```

```{Rcpp,echo=FALSE}
#include <Rcpp.h>
#include <math.h>

using namespace Rcpp;

//[[Rcpp::export]]
Rcpp::List diff3PunktFloat(const float x, const int r){
  // Array der ersten 100 Werte:
    Rcpp::NumericVector xValue(100);
    Rcpp::NumericVector yValue(100);
  // Quelltext
    for (int i = r; i<=99+r; i++){
      xValue[i-r] = (float)1./i;
      yValue[i-r] = (float)(exp(x+1./i) - exp(x-1./i))/(2./i);
    }
  // Rückgabe für eine grafische Wiedergabe
    return List::create(Named("x") = xValue, Named("y") = yValue);
}
```


```{r, echo=FALSE}
x = -1
r = 5
double2 = diff2PunktDouble(x, r)
float2 = diff2PunktFloat(x, r)
double3 = diff3PunktDouble(x, r)
float3 = diff3PunktFloat(x, r)
double3$y[99]
float2$y[1]
```

```{r, echo=FALSE}
e1 = exp(-1)
plot(double2$x, double2$y-e1, "l", ylim=c(double3$y[99]-e1, float2$y[1]-e1), xlab = "h", ylab = "Abweichung", col = "dark blue")
lines(double3$x, double3$y-e1, "l", col = "blue")
lines(float2$x, float2$y-e1, "l", col = "red")
lines(float3$x, float3$y-e1, "l",  col = "orange")
legend(0.01,0.038,legend=c("2 Punkt Double", "2 Punkt Float", "3 Punkt Double", "3 Punkt Float"), col = c("dark blue", "red", "blue", "orange"), lty=1:1)
```





